### ISSUE TITLE
Python 3.8 issue: `cannot import name 'actions' from partially initialized module 'amti'

### ISSUE THREAD

**Issue by danyaljj** [allenai/amti#37]
I am getting this upon calling `amti` 
```
% amti
Traceback (most recent call last):
  File "/usr/local/bin/amti", line 9, in <module>
    from amti import clis
  File "/Users/danielk/Library/Python/3.8/lib/python/site-packages/amti/__init__.py", line 3, in <module>
    from amti import (
ImportError: cannot import name 'actions' from partially initialized module 'amti' (most likely due to a circular import) (/Users/danielk/Library/Python/3.8/lib/python/site-packages/amti/__init__.py)
```

**Comment by danyaljj** [comment]
Replicated the same issue on a different computer and with Python 3.8.
